author: "Эдди Османи"
title: "Паттерны для масштабируемых JavaScript приложений"

markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'makefile']
pygments: true

production_url: http://largescalejavascript.ru/
baseurl: /
permalink: /:title
