author: "Addy Osmani"
title: "Паттерны для масштабируемых JavaScript приложений"

markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'makefile']

production_url: http://largescalejavascript.ru/
baseurl: /
permalink: /:title